import { IconMedium } from "../utils/icons/IconComponent";

export const sideMenuData = [
  { id: 1, label: "Dashboard", icon: <IconMedium type="key" /> },
  { id: 2, label: "Product", icon: <IconMedium type="cube" /> },
  { id: 3, label: "Customers", icon: <IconMedium type="customer" /> },
  { id: 4, label: "Income", icon: <IconMedium type="wallet" /> },
  { id: 5, label: "Promote", icon: <IconMedium type="percent" /> },
  { id: 6, label: "Help", icon: <IconMedium type="help" /> },
];
export const tableData = [
  {
    id: 1,
    name: "Jane Cooper",
    company: "Microsoft",
    number: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: true,
  },
  {
    id: 2,
    name: "Floyd Miles",
    company: "Yahoo",
    number: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: false,
  },
  {
    id: 3,
    name: "Ronald Richards",
    company: "Adobe",
    number: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: false,
  },
  {
    id: 4,
    name: "Marvin McKinney",
    company: "Tesla",
    number: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: true,
  },
  {
    id: 5,
    name: "Jerome Bell",
    company: "Google",
    number: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: true,
  },
  {
    id: 6,
    name: "Kathryn Murphy",
    company: "Microsoft",
    number: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: true,
  },
  {
    id: 7,
    name: "Jacob Jones",
    company: "Yahoo",
    number: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: true,
  },
  {
    id: 8,
    name: "Kristin Watson",
    company: "Facebook",
    number: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: false,
  },
];
